source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MoABContactsManager_Example', :exclusive => true do
  pod "MoABContactsManager", :path => "../"
end

target 'MoABContactsManager_Tests', :exclusive => true do
  pod "MoABContactsManager", :path => "../"

end
